// For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. — John 3:16 (KJV)
async (pageChirho) => {
  const evidenceChirho = [];
  function checkChirho(okChirho, labelChirho) { if (!okChirho) throw new Error(labelChirho); evidenceChirho.push(labelChirho); }
  const errorsChirho = [];
  pageChirho.on('pageerror', (errorChirho) => errorsChirho.push(errorChirho.message));
  const writesChirho = [];
  let modeChirho = 'reject-chirho', releaseChirho = null;
  await pageChirho.unroute('**/api-chirho/**');
  await pageChirho.route('**/api-chirho/**', async (routeChirho) => {
    const requestChirho = routeChirho.request();
    if (['GET', 'HEAD'].includes(requestChirho.method())) return routeChirho.continue();
    writesChirho.push({ urlChirho: requestChirho.url(), methodChirho: requestChirho.method(), bodyChirho: requestChirho.postDataJSON() });
    if (modeChirho === 'network-chirho') return routeChirho.abort('failed');
    if (modeChirho === 'pending-chirho') await new Promise((resolveChirho) => { releaseChirho = resolveChirho; });
    if (modeChirho === 'reject-chirho') return routeChirho.fulfill({ status: 409, contentType: 'application/json', body: '{"errorChirho":"fixture conflict"}' });
    return routeChirho.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ confirmed_chirho: true, event_seq_chirho: 99999 }) });
  });
  await pageChirho.setViewportSize({ width: 1440, height: 1000 });
  await pageChirho.goto('http://127.0.0.1:5178/volumes-chirho/3/pages-chirho/151');
  await pageChirho.locator('.reading-token-chirho').first().waitFor();
  await pageChirho.waitForFunction(() => document.querySelector('.scan-canvas-chirho img')?.naturalWidth > 0);
  checkChirho(await pageChirho.locator('.reading-token-chirho').count() > 500, 'real snapshot path renders full-page words');
  const scanBoundsChirho = await pageChirho.getByRole('region', { name: 'Source scan' }).boundingBox();
  const textBoundsChirho = await pageChirho.getByRole('region', { name: 'Page transcription' }).boundingBox();
  checkChirho(scanBoundsChirho.x < textBoundsChirho.x, 'source left, transcription right');
  await pageChirho.getByRole('button', { name: 'ἐκρύσεις', exact: true }).click();
  const inputChirho = pageChirho.getByRole('textbox');
  checkChirho(await inputChirho.inputValue() === 'ἐκρύσεις', 'scan-linked Greek phrase opens in the line');
  checkChirho(await pageChirho.getByRole('dialog').count() === 0, 'no modal covers the page');
  checkChirho(await pageChirho.getByRole('img', { name: 'Magnified selected print with surrounding ink' }).isVisible(), 'padded magnifier visible');
  await inputChirho.fill('draft-chirho');
  await inputChirho.press('Tab');
  checkChirho(await inputChirho.inputValue() !== 'draft-chirho', 'Tab advances without saving');
  await inputChirho.press('Shift+Tab');
  checkChirho(await inputChirho.inputValue() === 'draft-chirho', 'Shift Tab restores unsaved text');
  await inputChirho.press('Enter');
  checkChirho(writesChirho.length === 0, 'plain Enter and focus changes never write');
  await inputChirho.fill('draft-chirho');
  await pageChirho.getByRole('button', { name: 'Confirm & next' }).click();
  await pageChirho.getByRole('alert').waitFor();
  checkChirho(await inputChirho.inputValue() === 'draft-chirho' && (await pageChirho.getByRole('alert').innerText()).includes('changed'), 'HTTP conflict preserves draft and selection');
  checkChirho(writesChirho.length === 1 && writesChirho[0].bodyChirho.kind_chirho === 'segment-chirho' && !('proposed_box_chirho' in writesChirho[0].bodyChirho), 'segment confirmation carries source precondition, not box changes');
  modeChirho = 'network-chirho';
  await pageChirho.getByRole('button', { name: 'Confirm & next' }).click();
  await pageChirho.waitForFunction(() => document.querySelector('[role="alert"]')?.textContent.includes('connection'));
  checkChirho(await inputChirho.inputValue() === 'draft-chirho', 'connection loss preserves draft');
  modeChirho = 'pending-chirho';
  await pageChirho.getByRole('button', { name: 'Confirm & next' }).click();
  await pageChirho.waitForFunction(() => document.querySelector('.confirm-reading-chirho')?.disabled);
  const beforePendingChirho = writesChirho.length;
  await pageChirho.getByRole('button', { name: 'Saving…' }).dispatchEvent('click');
  await inputChirho.dispatchEvent('keydown', { key: 'Enter', ctrlKey: true });
  checkChirho(writesChirho.length === beforePendingChirho, 'in-flight confirmation blocks duplicate requests');
  modeChirho = 'success-chirho'; releaseChirho();
  await pageChirho.waitForFunction(() => document.querySelector('textarea')?.value === 'que' && !document.querySelector('textarea')?.disabled);
  checkChirho((await pageChirho.locator('.reader-intro-chirho').innerText()).includes('0 /'), 'mock acknowledgement cannot paint a confirmation absent from refreshed server state');
  checkChirho(await inputChirho.inputValue() === 'que', 'successful confirmation advances to next reading');
  await inputChirho.fill('word-draft-chirho');
  await inputChirho.press('Control+Enter');
  await pageChirho.waitForFunction(() => { const editorChirho = document.querySelector('textarea'); return editorChirho && editorChirho.value !== 'word-draft-chirho' && !editorChirho.disabled; });
  checkChirho(writesChirho.at(-1).bodyChirho.kind_chirho === 'word-chirho', 'word correction uses source-matched confirmation endpoint');
  await pageChirho.getByRole('button', { name: 'ἐκρύσεις', exact: true }).count();
  await pageChirho.getByRole('button', { name: 'ἐκρύσεις', exact: true }).click();
  await pageChirho.getByRole('button', { name: 'Adjust box', exact: true }).click();
  const selectedBoxChirho = pageChirho.locator('.scan-box-chirho[aria-pressed="true"]');
  const beforeBoxChirho = await selectedBoxChirho.boundingBox();
  await pageChirho.mouse.move(beforeBoxChirho.x + beforeBoxChirho.width / 2, beforeBoxChirho.y + beforeBoxChirho.height / 2);
  await pageChirho.mouse.down(); await pageChirho.mouse.move(beforeBoxChirho.x + beforeBoxChirho.width / 2 + 9, beforeBoxChirho.y + beforeBoxChirho.height / 2 + 5, { steps: 4 }); await pageChirho.mouse.up();
  const afterBoxChirho = await selectedBoxChirho.boundingBox();
  checkChirho(afterBoxChirho.x > beforeBoxChirho.x + 7 && afterBoxChirho.y > beforeBoxChirho.y + 3, 'direct pointer drag moves source-coordinate box');
  checkChirho(await pageChirho.getByRole('button', { name: 'Adjust box', exact: true }).getAttribute('aria-pressed') === 'true', 'drag retains box-adjustment mode');
  const cornerChirho = pageChirho.getByRole('button', { name: 'Resize selected box with arrow keys or drag' });
  await cornerChirho.focus(); await cornerChirho.press('Shift+ArrowRight');
  checkChirho((await selectedBoxChirho.boundingBox()).width > afterBoxChirho.width, 'keyboard-accessible resize changes width');
  await pageChirho.getByRole('button', { name: 'Adjust box', exact: true }).click();
  checkChirho(await pageChirho.getByRole('button', { name: 'Confirm & next' }).isDisabled(), 'dirty geometry blocks confirmation even after repair mode closes');
  const beforeRepairWritesChirho = writesChirho.length;
  const downloadPromiseChirho = pageChirho.waitForEvent('download');
  await pageChirho.getByRole('button', { name: 'Export box-repair draft' }).click();
  const downloadChirho = await downloadPromiseChirho;
  const streamChirho = await downloadChirho.createReadStream();
  let jsonChirho = ''; for await (const chunkChirho of streamChirho) jsonChirho += chunkChirho.toString();
  const draftChirho = JSON.parse(jsonChirho);
  checkChirho(draftChirho.approved_chirho === false && draftChirho.repairs_chirho.length === 1, 'download is explicitly unsubmitted and unapproved');
  checkChirho(draftChirho.repairs_chirho[0].original_box_chirho.xChirho !== draftChirho.repairs_chirho[0].proposed_box_chirho.xChirho, 'download retains original and proposed coordinates');
  checkChirho(writesChirho.length === beforeRepairWritesChirho, 'move, resize and export never write canonical state');
  await pageChirho.evaluate(() => {
    window.originalConfirmChirho = window.confirm; window.confirmCallsChirho = 0; window.confirm = () => { window.confirmCallsChirho++; return false; };
    window.originalSetItemChirho = Storage.prototype.setItem;
    Storage.prototype.setItem = function(keyChirho, valueChirho) { if (keyChirho === 'hottp-page-drafts-v1-chirho') throw new Error('fixture quota failure'); return window.originalSetItemChirho.call(this, keyChirho, valueChirho); };
  });
  await pageChirho.getByRole('link', { name: 'Next page', exact: true }).click();
  await pageChirho.waitForFunction(() => window.confirmCallsChirho === 1);
  checkChirho(pageChirho.url().endsWith('/151') && await pageChirho.evaluate(() => window.confirmCallsChirho === 1), 'failed-backup navigation can be cancelled');
  await pageChirho.evaluate(() => { window.confirm = window.originalConfirmChirho; Storage.prototype.setItem = window.originalSetItemChirho; });
  await pageChirho.screenshot({ path: '/Users/hallelujah/dev-chirho/friends-chirho/andrewbeth-chirho/hottp-chirho/workspace-chirho/reviewer-ui-chirho/26-09-18-lace-repair-chirho.png', fullPage: true });
  await pageChirho.getByRole('button', { name: 'Discard draft', exact: true }).click();
  checkChirho(await pageChirho.getByRole('button', { name: 'Confirm & next' }).isEnabled(), 'discard restores original box and confirmation eligibility');
  const layoutChirho = [];
  for (const widthChirho of [1440, 1024, 768, 390]) {
    await pageChirho.setViewportSize({ width: widthChirho, height: widthChirho === 1440 ? 1000 : 850 });
    const sizesChirho = await pageChirho.evaluate(() => ({ documentChirho: document.documentElement.scrollWidth, viewportChirho: innerWidth }));
    checkChirho(sizesChirho.documentChirho <= sizesChirho.viewportChirho, `no horizontal overflow at ${widthChirho}px`);
    layoutChirho.push({ widthChirho, ...sizesChirho });
    if (widthChirho === 390) await pageChirho.screenshot({ path: '/Users/hallelujah/dev-chirho/friends-chirho/andrewbeth-chirho/hottp-chirho/workspace-chirho/reviewer-ui-chirho/26-09-18-lace-mobile-chirho.png', fullPage: true });
  }
  await pageChirho.setViewportSize({ width: 1440, height: 1000 });
  await pageChirho.screenshot({ path: '/Users/hallelujah/dev-chirho/friends-chirho/andrewbeth-chirho/hottp-chirho/workspace-chirho/reviewer-ui-chirho/26-09-18-lace-desktop-chirho.png', fullPage: true });
  checkChirho(errorsChirho.length === 0, 'no runtime page errors');
  await pageChirho.unroute('**/api-chirho/**');
  await pageChirho.reload();
  await pageChirho.getByRole('button', { name: 'ἐκρύσεις', exact: true }).click();
  await pageChirho.screenshot({ path: '/Users/hallelujah/dev-chirho/friends-chirho/andrewbeth-chirho/hottp-chirho/workspace-chirho/reviewer-ui-chirho/26-09-18-lace-desktop-chirho.png', fullPage: true });
  await pageChirho.setViewportSize({ width: 390, height: 850 });
  await pageChirho.getByRole('textbox').click();
  await pageChirho.screenshot({ path: '/Users/hallelujah/dev-chirho/friends-chirho/andrewbeth-chirho/hottp-chirho/workspace-chirho/reviewer-ui-chirho/26-09-18-lace-mobile-chirho.png', fullPage: true });
  await pageChirho.setViewportSize({ width: 1440, height: 1000 });
  return { assertionsChirho: evidenceChirho.length, evidenceChirho, writesInterceptedChirho: writesChirho.length, layoutChirho, errorsChirho };
}
