// For God so loved the world that he gave his only begotten Son,
// that whoever believes in him should not perish but have eternal life. John 3:16

/**
 * Turn the CRNN corpus triage (workspace-chirho/word-ocr-chirho/triage-chirho.json)
 * into an idempotent SQL file that populates ocr_suggestions_chirho in the
 * app D1.
 *
 * Each AUTO/REVIEW read becomes an INSERT ... SELECT that RESOLVES the
 * target word_id + page_id BY page-number + bbox match AT APPLY TIME — so
 * the same SQL is correct against whichever D1 it runs on (local dev or
 * deployed), and never needs the script to pre-query the database. REJECT
 * (contamination) rows are skipped. Already human-confirmed words are
 * skipped (is_human_confirmed_chirho = 0 guard) so suggestions never
 * shadow finished work. INSERT OR IGNORE + UNIQUE(word_id, model) makes
 * re-runs idempotent.
 *
 * It does NOT touch any database — it only writes a .sql file for review,
 * applied by the user with:
 *   wrangler d1 execute <db> --file=workspace-chirho/word-ocr-chirho/load-ocr-suggestions-chirho.sql [--remote]
 *
 * Run:  bun src-chirho/load-ocr-suggestions-chirho.ts [--vol=1] [--model=crnn-ctc-v1-chirho] [--triage=path]
 *
 * --triage lets a per-volume probe (read_volume_page_chirho.py --out-triage) feed
 * its own triage JSON without clobbering the canonical vol-1 corpus triage.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const PROJECT_ROOT_CHIRHO = resolve(import.meta.dir, "..");
const DEFAULT_TRIAGE_PATH_CHIRHO = resolve(
  PROJECT_ROOT_CHIRHO,
  "workspace-chirho/word-ocr-chirho/triage-chirho.json",
);
const OUT_SQL_PATH_CHIRHO = resolve(
  PROJECT_ROOT_CHIRHO,
  "workspace-chirho/word-ocr-chirho/load-ocr-suggestions-chirho.sql",
);
const BBOX_TOLERANCE_CHIRHO = 3; // crop coords are int; D1 bbox is real
const CROP_RE_CHIRHO = /^p(\d+)-x(\d+)-y(\d+)-chirho\.png$/;

interface TriageRecordChirho {
  cropChirho: string;
  pageChirho: number | null;
  readingChirho: string;
  confChirho: number;
  wlcVerdictChirho: string;
  bucketChirho: "AUTO" | "REVIEW" | "REJECT";
  // tesseract saw Hebrew chars in this crop. REQUIRED gate: the CRNN has no
  // "not Hebrew" output and confidently misreads French (avec, comme, …) as
  // short WLC-exact Hebrew, so WLC-membership alone does NOT screen
  // contamination (~71% of un-gold AUTO is French/punct). Only surface
  // suggestions on crops an independent signal also calls Hebrew.
  tessHebrewChirho: boolean;
}

const sqlEscapeChirho = (sChirho: string): string => sChirho.replace(/'/g, "''");

function mainChirho(): void {
  const argsChirho = process.argv.slice(2);
  let volChirho = 1;
  let modelChirho = "crnn-ctc-v1-chirho";
  let triagePathChirho = DEFAULT_TRIAGE_PATH_CHIRHO;
  for (const aChirho of argsChirho) {
    if (aChirho.startsWith("--vol=")) volChirho = Number(aChirho.split("=")[1]);
    if (aChirho.startsWith("--model=")) modelChirho = aChirho.split("=")[1];
    if (aChirho.startsWith("--triage=")) {
      triagePathChirho = resolve(PROJECT_ROOT_CHIRHO, aChirho.split("=").slice(1).join("="));
    }
  }
  if (!existsSync(triagePathChirho)) {
    console.error(`no triage at ${triagePathChirho}; run triage_corpus_chirho.py (or read_volume_page_chirho.py --out-triage) first.`);
    process.exit(1);
  }
  const triageChirho = JSON.parse(readFileSync(triagePathChirho, "utf8"));
  const recordsChirho: TriageRecordChirho[] = triageChirho.recordsChirho ?? [];

  const linesChirho: string[] = [
    "-- For God so loved the world that he gave his only begotten Son,",
    "-- that whoever believes in him should not perish but have eternal life. John 3:16",
    "-- GENERATED by src-chirho/load-ocr-suggestions-chirho.ts — do not edit by hand.",
    `-- model=${modelChirho} vol=${volChirho} bbox_tolerance=${BBOX_TOLERANCE_CHIRHO}px`,
    `-- triage=${triagePathChirho.replace(PROJECT_ROOT_CHIRHO + "/", "")}`,
    "BEGIN TRANSACTION;",
  ];

  let emittedChirho = 0;
  let skippedRejectChirho = 0;
  let skippedBadNameChirho = 0;
  let skippedNonHebrewChirho = 0;
  for (const rChirho of recordsChirho) {
    if (rChirho.bucketChirho === "REJECT") {
      skippedRejectChirho += 1;
      continue;
    }
    // is-Hebrew gate (see TriageRecordChirho.tessHebrewChirho): never surface
    // a Hebrew suggestion on a crop tesseract did not read as Hebrew.
    if (!rChirho.tessHebrewChirho) {
      skippedNonHebrewChirho += 1;
      continue;
    }
    if (!rChirho.readingChirho || rChirho.readingChirho.length < 2) continue;
    const mChirho = rChirho.cropChirho.match(CROP_RE_CHIRHO);
    if (!mChirho) {
      skippedBadNameChirho += 1;
      continue;
    }
    const pageChirho = Number(mChirho[1]);
    const xMinChirho = Number(mChirho[2]);
    const yMinChirho = Number(mChirho[3]);
    const textChirho = sqlEscapeChirho(rChirho.readingChirho);
    const verdictChirho = sqlEscapeChirho(rChirho.wlcVerdictChirho);
    const cropChirho = sqlEscapeChirho(rChirho.cropChirho);
    linesChirho.push(
      `INSERT OR IGNORE INTO ocr_suggestions_chirho ` +
        `(word_id_chirho, page_id_chirho, suggested_text_chirho, confidence_chirho, ` +
        `wlc_verdict_chirho, bucket_chirho, model_chirho, crop_chirho) ` +
        `SELECT w.id_chirho, p.id_chirho, '${textChirho}', ${rChirho.confChirho}, ` +
        `'${verdictChirho}', '${rChirho.bucketChirho}', '${modelChirho}', '${cropChirho}' ` +
        `FROM words_chirho w ` +
        `JOIN scanlines_chirho s ON s.id_chirho = w.scanline_id_chirho ` +
        `JOIN pages_chirho p ON p.id_chirho = s.page_id_chirho ` +
        `WHERE p.volume_number_chirho = ${volChirho} ` +
        `AND p.page_number_chirho = ${pageChirho} ` +
        `AND ABS(w.x_min_chirho - ${xMinChirho}) <= ${BBOX_TOLERANCE_CHIRHO} ` +
        `AND ABS(w.y_min_chirho - ${yMinChirho}) <= ${BBOX_TOLERANCE_CHIRHO} ` +
        `AND w.is_human_confirmed_chirho = 0 ` +
        `LIMIT 1;`,
    );
    emittedChirho += 1;
  }
  linesChirho.push("COMMIT;");
  writeFileSync(OUT_SQL_PATH_CHIRHO, linesChirho.join("\n") + "\n", "utf8");

  console.log(`triage records: ${recordsChirho.length}`);
  console.log(`  emitted INSERTs (AUTO+REVIEW, tess-Hebrew, len>=2): ${emittedChirho}`);
  console.log(`  skipped REJECT (contamination): ${skippedRejectChirho}`);
  console.log(`  skipped tess-NON-Hebrew (is-Hebrew gate): ${skippedNonHebrewChirho}`);
  console.log(`  skipped unparseable crop name: ${skippedBadNameChirho}`);
  console.log(`wrote ${OUT_SQL_PATH_CHIRHO}`);
  console.log(
    `\nEach INSERT self-resolves word_id by page+bbox at apply time and ` +
      `skips human-confirmed words. Apply (after migration 0013) with:\n` +
      `  cd app-chirho && wrangler d1 execute <db-chirho> ` +
      `--file=../workspace-chirho/word-ocr-chirho/load-ocr-suggestions-chirho.sql [--remote]\n` +
      `Tip: a row that matched 0 words is a silent no-op (INSERT...SELECT). ` +
      `Verify match rate after apply with: SELECT COUNT(*) FROM ocr_suggestions_chirho;`,
  );
}

mainChirho();
